### ISSUE TITLE
Change the time format in the GPS JavaScript

### ISSUE THREAD

**Issue by Num2** [britzke/rennspur#28] opened 2017-01-12 20:09 UTC
The date format used in the javascript(Date.now) isn't compatible with Java backend.
It should be changed to fit the Java Date Format
Suggestion:

`var date = new Date().toISOString().substr(0, 19);`
`date = date.replace("T"," ")`

Maybe there is an even more easy way, the code provided is just a quick hack that worked.

**Comment by britzke** [comment] 2017-01-12 21:32
Maybe the DateAdapter could parse a date with ISO format?

**Comment by britzke** [comment] 2017-01-13 06:36
As the date format, which the GPS component emits, causes the issue #27, this is a duplicate of it.

**Closed by britzke** 2017-01-13 06:36 UTC
Labels: duplicate
